int main()
{
	char *s_hidden = "hi low";
	int		a = -4;
	int		b = 0;
	char	c = 'a';
	int		d = 2147483647;
	int		e = -2147483648;
	int		f = 42;
	int		g = 25;
	int		h = 4200;
	int		i = 8;
	int		j = -12;
	int		k = 123456789;
	int		l = 0;
	unsigned int x = 5;
	unsigned int X = 8;
	int		m = -12345678;
	char	*n = "abcdefghijklmnop";
	char	*o = "-a";
	char	*p = "-12";
	char	*q = "0";
	char	*r = "%%";
	char	*s = "-2147483648";
	char	*t = "0x12345678";
	char	*u = "-0";
	int or = 0;
	int my = 0;
or = printf("\n%i, %d, %d, %d, %d, %s, %c, %d, %u, %x, %X|\n", i, j, k, l, m, n, c, c, j, j, j);
my = ft_printf("\n%i, %d, %d, %d, %d, %s, %c, %d, %u, %x, %X|\n", i, j, k, l, m, n, c, c, j, j, j);
printf("\nor: %d\n", or);
ft_printf("\nmy: %d\n", my);
or = printf("or: %0i, %0d, %0d, %0d, %0d, %0d, %0d, %0d|\n", i, j, k, l, m, c, e, d);
my = ft_printf("my: %0i, %0d, %0d, %0d, %0d, %0d, %0d, %0d|\n", i, j, k, l, m, c, e, d);
printf("\nor: %d\n", or);
ft_printf("\nmy: %d\n", my);
printf("%09s\n", s_hidden);
ft_printf("\n%09s", s_hidden);
ft_printf("\nmy:|%5\n", 4);
printf("\nor:|%5\n", 4);
return (0);
}
